version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /sample-python-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /sample-python-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /sample-python-app/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.11
    
    pre-build:
      commands:
        - echo "Installing dependencies..."
        - pip install -r requirements.txt

    build:
      commands:
        - echo "Building Docker image"
        - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
        - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sample-python-flask:latest" .
        - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sample-python-flask:latest"

artifacts:
  files:
    - '**/*'
  base-directory: .    